import { useEffect, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { Activity, ArrowDown, ArrowDownToLine, ArrowRight, ArrowUp, Check, ChevronDown, CircleHelp, Clock3, Droplet, FileKey2, FolderOpen, Globe2, KeyRound, Laptop, LoaderCircle, LockKeyhole, MoreHorizontal, Plus, Power, RefreshCw, Settings2, Shield, ShieldCheck, Trash2, Wifi, X } from 'lucide-react';
import type { Profile, Snapshot } from './types';

const initial: Snapshot = { profiles: [], settings: { autoReconnect: true, launchAtLogin: false, minimizeToTray: true, enginePath: '' }, connection: { status: 'disconnected', profileId: null, connectedAt: null, localIp: null, remoteIp: null, received: 0, sent: 0, reconnects: 0, message: 'Ready when you are.', prompt: null }, logs: [], engine: { available: false, path: '', version: null }, platform: 'darwin', vaultAvailable: false, version: '0.1.0' };
const labels = { disconnected: 'Disconnected', connected: 'Connected', connecting: 'Connecting', reconnecting: 'Reconnecting', 'credentials-required': 'Sign-in needed', disconnecting: 'Disconnecting', error: 'Connection stopped' };
const bytes = (value: number) => value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`;
const duration = (since: string | null, now: number) => { const seconds = since ? Math.max(0, Math.floor((now - new Date(since).getTime()) / 1000)) : 0; return [Math.floor(seconds / 3600), Math.floor(seconds / 60) % 60, seconds % 60].map(n => String(n).padStart(2, '0')).join(':'); };

function Toggle({ value, onChange, label, disabled = false }: { value: boolean; onChange: () => void; label: string; disabled?: boolean }) {
  return <button className={`toggle ${value ? 'on' : ''}`} role="switch" aria-checked={value} aria-label={label} disabled={disabled} onClick={onChange}><span /></button>;
}

function Modal({ title, children, close }: { title: string; children: ReactNode; close: () => void }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement; ref.current?.querySelector<HTMLElement>('input, button')?.focus(); return () => previous?.focus(); }, []);
  return <div className="modal-overlay" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div ref={ref} className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onKeyDown={e => {
    if (e.key === 'Escape') close();
    if (e.key === 'Tab') { const items = ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select'); if (!items?.length) return; const first = items[0], last = items[items.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } }
  }}><div className="modal-heading"><div className="icon-box violet"><KeyRound size={21} /></div><button className="icon-button" aria-label="Close dialog" onClick={close}><X size={19} /></button></div><h2 id="modal-title">{title}</h2>{children}</div></div>;
}

export function App() {
  const [state, setState] = useState<Snapshot>(initial);
  const [page, setPage] = useState<'connection' | 'profiles' | 'activity' | 'settings'>('connection');
  const [selected, setSelected] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [now, setNow] = useState(Date.now());
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [remember, setRemember] = useState(true);
  const [menu, setMenu] = useState('');
  const [renaming, setRenaming] = useState<Profile | null>(null);
  const [name, setName] = useState('');
  const api = window.dropovpn;
  useEffect(() => { if (!api) return; let active = true; api.snapshot().then(s => { if (active) setState(s); }).catch(e => setError(e.message)); const off = api.onChange(setState); return () => { active = false; off(); }; }, [api]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { if (!state.profiles.some(p => p.id === selected)) setSelected(state.profiles[0]?.id || ''); }, [state.profiles, selected]);
  useEffect(() => { setPassword(''); }, [state.connection.prompt, state.connection.status === 'credentials-required']);
  const connection = state.connection;
  const connected = connection.status === 'connected';
  const active = !['disconnected', 'error'].includes(connection.status);
  const transitioning = ['connecting', 'reconnecting', 'disconnecting'].includes(connection.status);
  const profile = state.profiles.find(p => p.id === (active ? connection.profileId : selected));
  async function run(work: () => Promise<unknown>) { setBusy(true); setError(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong. Please try again.'); } finally { setBusy(false); } }
  const doImport = () => api && run(async () => { const ids = await api.importProfiles(); if (ids.length) setSelected(ids[0]); });
  const setting = (key: 'autoReconnect' | 'launchAtLogin' | 'minimizeToTray') => api && run(() => api.settings({ [key]: !state.settings[key] }));
  const selectProfile = (p: Profile) => { setSelected(p.id); setPage('connection'); };
  const submitCredentials = (event: FormEvent) => { event.preventDefault(); if (api) void run(async () => { await api.credentials({ username, password, remember, privateKey: connection.prompt === 'Private Key' }); setPassword(''); }); };

  const profileRows = (full = false) => state.profiles.length ? <div className="profile-list">{state.profiles.map(p => <div className={`profile-row ${selected === p.id ? 'selected' : ''}`} key={p.id}>
    <button className="profile-select" onClick={() => selectProfile(p)}><span className="profile-icon"><Globe2 size={20} /></span><span className="profile-text"><strong>{p.name}</strong><small>{p.server}</small></span></button>
    {p.hasCredentials && <span className="saved-label"><LockKeyhole size={12} /> Saved</span>}<span className="protocol">{p.protocol}</span>
    {connection.profileId === p.id && active ? <span className={`profile-state ${connected ? 'live' : ''}`}><i />{labels[connection.status]}</span> : <button className="text-button" disabled={active} onClick={() => selectProfile(p)}>{selected === p.id ? <><Check size={14} /> Selected</> : 'Select'}</button>}
    <div className="menu-wrapper"><button className="icon-button" aria-label={`Options for ${p.name}`} aria-expanded={menu === p.id} onClick={() => setMenu(menu === p.id ? '' : p.id)}><MoreHorizontal size={20} /></button>{menu === p.id && <><button className="menu-dismiss" tabIndex={-1} aria-label="Dismiss profile options" onClick={() => setMenu('')} /><div className="profile-menu"><button onClick={() => { setRenaming(p); setName(p.name); setMenu(''); }}>Rename profile</button><button disabled={!p.hasCredentials} onClick={() => { setMenu(''); if (api) void run(() => api.forget(p.id)); }}>Forget saved password</button><button className="danger" onClick={() => { setMenu(''); if (api) void run(() => api.remove(p.id)); }}><Trash2 size={14} /> Remove profile</button></div></>}</div>
  </div>)}</div> : <div className={`empty-profiles ${full ? 'large' : ''}`}><div className="file-illustration"><FileKey2 size={28} /><span>+</span></div><div><h3>Your next connection starts here</h3><p>Import an .ovpn file from your VPN provider or IT team.</p></div><button className="button secondary" disabled={!api || busy} onClick={doImport}><Plus size={16} /> Import profile</button></div>;

  return <div className={`app-shell platform-${state.platform}`}>
    <aside className="sidebar"><div className="window-drag" /><a className="brand" href="#" onClick={e => { e.preventDefault(); setPage('connection'); }}><span className="brand-icon"><Droplet fill="currentColor" size={23} /><span /></span>dropo<span className="brand-vpn">vpn</span></a><div className="workspace-label">YOUR WORKSPACE</div>
      <nav aria-label="Main navigation">{([{ id: 'connection', label: 'Connection', Icon: Shield }, { id: 'profiles', label: 'VPN profiles', Icon: FolderOpen }, { id: 'activity', label: 'Activity', Icon: Activity }] as const).map(({ id, label, Icon }) => <button key={id} className={`nav-item ${page === id ? 'current' : ''}`} aria-current={page === id ? 'page' : undefined} onClick={() => setPage(id)}><Icon size={18} />{label}{id === 'profiles' && <span className="nav-count">{state.profiles.length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="quiet-card"><span className="quiet-icon"><RefreshCw size={17} /></span><strong>A little less reconnecting.</strong><p>A little more getting things done.</p><span className="quiet-line" /></div><button className={`nav-item ${page === 'settings' ? 'current' : ''}`} onClick={() => setPage('settings')}><Settings2 size={18} />Settings</button><button className="nav-item help" onClick={() => api ? void run(() => api.help()) : setPage('settings')}><CircleHelp size={18} />Help & resources<ArrowUp size={13} className="external-arrow" /></button><div className="sidebar-footer"><span className="small-logo"><Droplet size={14} /></span>DropoVPN <span>v{state.version}</span></div></div>
    </aside>
    <div className="main-shell"><div className="titlebar"><span><i /> YOUR CONNECTION, SIMPLIFIED</span><div><Laptop size={13} />{api ? (state.platform === 'darwin' ? 'macOS' : 'Windows') : 'Desktop preview'}</div></div>
      <main><header className="page-header"><div><div className="eyebrow">{page === 'connection' ? 'A QUIETER WAY TO CONNECT' : 'MAKE YOURSELF AT HOME'}</div><h1>{page === 'connection' ? 'Your connection.' : page === 'profiles' ? 'VPN profiles.' : page === 'activity' ? 'Connection activity.' : 'Just your preferences.'}</h1><p>{page === 'connection' ? 'Stay connected. We’ll take care of the reconnecting.' : page === 'profiles' ? 'Your familiar networks, always within reach.' : page === 'activity' ? 'A clear view of what’s happening behind the scenes.' : 'A few small settings for a smoother day.'}</p></div><button className="button secondary import-top" disabled={!api || busy} onClick={doImport}><Plus size={16} />Import profile</button></header>
      {!api && <div className="notice"><Laptop size={17} /><span>This is a preview. Open the desktop app to import profiles and connect.</span></div>}
      {error && <div className="notice error" role="alert"><CircleHelp size={17} /><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={() => setError('')}><X size={15} /></button></div>}
      {connection.status === 'error' && <div className="notice error" role="alert"><CircleHelp size={17} /><span>{connection.message}</span><button className="text-button" onClick={() => setPage('activity')}>View activity<ArrowRight size={14} /></button></div>}
      {page === 'connection' && <>
        <section className={`connection-card ${connected ? 'is-connected' : ''}`} aria-label="VPN connection">
          <div className="card-topline"><span className="card-overline">CONNECTION STATUS</span><span className={`status-pill ${connected ? 'green' : transitioning ? 'purple' : ''}`}><i className={transitioning ? 'pulse' : ''} />{labels[connection.status]}</span></div>
          <div className="connection-body"><div className="connection-info"><div className={`hero-icon ${connected ? 'green' : ''}`}>{connected ? <ShieldCheck size={24} /> : <Shield size={24} />}</div><h2>{connected ? 'A little peace of mind.' : transitioning ? 'Finding your connection.' : connection.status === 'error' ? 'Let’s get you connected.' : 'Your space. Connected.'}</h2><p className="connection-copy">{connected ? 'Your tunnel is active. Settle in and keep going.' : transitioning ? connection.message : 'A secure connection is just one click away.'}</p>
            <div className="profile-picker"><Globe2 size={17} /><select aria-label="Choose a VPN profile" value={profile?.id || ''} disabled={!state.profiles.length || active} onChange={e => setSelected(e.target.value)}>{!state.profiles.length && <option value="">Choose a VPN profile</option>}{state.profiles.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><ChevronDown size={15} /></div>
            <button className={`button primary connect-button ${connected ? 'disconnect-button' : ''}`} disabled={busy || connection.status === 'disconnecting' || !api || (!active && !profile)} onClick={() => api && run(() => active ? api.disconnect() : api.connect(selected))}>{transitioning ? <LoaderCircle className="spin" size={17} /> : <Power size={17} />}{active ? (transitioning ? 'Cancel connection' : 'Disconnect') : 'Connect to VPN'}{!active && <ArrowRight size={16} />}</button>
            <div className="connection-note"><LockKeyhole size={12} />{connected ? 'Encrypted with OpenVPN' : 'Your credentials stay on this device'}</div>
          </div><div className="connection-art" aria-hidden="true"><div className="orbital orbital-one" /><div className="orbital orbital-two" /><div className="orbital orbital-three" /><div className="art-grid" /><div className="art-node node-one"><Laptop size={18} /></div><div className="art-node node-two"><Globe2 size={19} /></div><div className="art-node node-three"><LockKeyhole size={16} /></div><div className={`power-orb ${transitioning ? 'breathing' : ''}`}><div><Droplet size={61} strokeWidth={1.35} />{connected && <span className="orb-check"><Check size={13} /></span>}</div></div><div className="orbit-label"><span />{connected ? 'A SECURE LITTLE WORLD' : 'READY FOR YOUR NEXT CONNECTION'}</div></div></div>
          <div className="connection-stats"><div><Clock3 size={16} /><span>Session time<strong>{duration(connection.connectedAt, now)}</strong></span></div><div><ArrowDown size={17} /><span>Downloaded<strong>{bytes(connection.received)}</strong></span></div><div><ArrowUp size={17} /><span>Uploaded<strong>{bytes(connection.sent)}</strong></span></div><div><Wifi size={16} /><span>VPN address<strong>{connection.localIp || 'Not connected'}</strong></span></div></div>
        </section>
        <div className="features-grid"><div className="feature-card"><span className="icon-box violet"><RefreshCw size={20} /></span><div><h3>Find your way back <span className="mini-badge">AUTO</span></h3><p>Connection drops? We’ll reconnect for you.</p></div><Toggle value={state.settings.autoReconnect} onChange={() => setting('autoReconnect')} label="Automatic reconnection" disabled={!api || busy} /></div><div className="feature-card"><span className="icon-box cream"><KeyRound size={20} /></span><div><h3>One less password to type</h3><p>{profile?.hasCredentials ? 'Your password is saved securely on this device.' : 'Choose “Remember me” when you sign in.'}</p></div><LockKeyhole className="feature-end" size={16} /></div></div>
        <section className="profiles-section"><div className="section-heading"><h2>Your VPN profiles <span>{state.profiles.length}</span></h2><button className="text-button" onClick={() => setPage('profiles')}>Manage profiles<ArrowRight size={14} /></button></div>{profileRows()}</section>
        <div className="bottom-note"><ShieldCheck size={14} /><span>Made for fewer interruptions. Built on OpenVPN.</span><span className="local-note"><i /> Stored locally. Always.</span></div>
      </>}
      {page === 'profiles' && <><section className="panel"><div className="section-heading"><h2>Saved connections <span>{state.profiles.length}</span></h2><span className="subtle">.ovpn profiles</span></div>{profileRows(true)}</section><div className="info-panel"><FileKey2 size={23} /><div><h3>Bring your own connection</h3><p>Import an OpenVPN profile from your provider or IT team. Certificates can be embedded in the file or stored alongside it. DropoVPN supports username/password and certificate authentication.</p></div></div></>}
      {page === 'activity' && <section className="panel activity-panel"><div className="section-heading"><h2>Session activity <span>{state.logs.length}</span></h2><button className="text-button" disabled={!api || !state.logs.length} onClick={() => api && run(() => api.clearLogs())}><Trash2 size={14} />Clear activity</button></div>{state.logs.length ? <div className="logs" aria-label="Connection events">{[...state.logs].reverse().map(log => <div className={`log-row ${log.level}`} key={log.id}><span className="log-dot" /><time>{new Date(log.time).toLocaleTimeString()}</time><span>{log.message}</span></div>)}</div> : <div className="empty-activity"><span className="icon-box violet"><Activity size={26} /></span><h3>All quiet here.</h3><p>Connection events will appear here as you use DropoVPN.</p></div>}<div className="panel-footer"><LockKeyhole size={13} />Activity is kept in memory. Password messages are never shown.</div></section>}
      {page === 'settings' && <>
        <section className="panel settings-panel"><h2>Make the connection yours</h2>{[{ key: 'autoReconnect' as const, title: 'Automatically reconnect', text: 'Recover from network interruptions and reconnect after sleep.', Icon: RefreshCw }, { key: 'launchAtLogin' as const, title: 'Open at login', text: 'Have DropoVPN ready when you start your computer.', Icon: Power }, { key: 'minimizeToTray' as const, title: 'Keep running in the background', text: 'Closing the window keeps your connection in the menu bar or tray.', Icon: Laptop }].map(({ key, title, text, Icon }) => <div className="setting-row" key={key}><Icon size={19} /><div><h3>{title}</h3><p>{text}</p></div><Toggle label={title} value={state.settings[key]} onChange={() => setting(key)} disabled={!api || busy} /></div>)}</section>
        <section className="panel engine-panel"><div className="section-heading"><h2>OpenVPN engine</h2><span className={`status-pill ${state.engine.available ? 'green' : ''}`}><i />{state.engine.available ? `${state.engine.bundled ? 'Included · ' : ''}v${state.engine.version}` : 'Setup needed'}</span></div><p>DropoVPN includes OpenVPN in the macOS app and sets up the engine and network driver during Windows installation. Starting a tunnel still requires administrator permission.</p>{state.engine.available ? <div className="engine-path"><Check size={15} /><code>{state.engine.bundled ? 'Included with DropoVPN' : state.engine.path}</code></div> : <div className="engine-install"><ArrowDownToLine size={19} /><div><strong>{state.platform === 'darwin' ? 'Repair the included OpenVPN engine' : 'Repair the included OpenVPN setup'}</strong>{state.platform === 'darwin' ? <p>Reinstall DropoVPN to restore the bundled engine.</p> : <p>Run the DropoVPN installer again to repair OpenVPN and its network driver.</p>}</div></div>}<div className="button-row"><button className="button secondary" disabled={!api || busy} onClick={() => api && run(() => api.checkEngine())}><RefreshCw size={15} />Check installation</button><button className="text-button" disabled={!api || busy} onClick={() => api && run(() => api.selectEngine())}>Locate executable<ArrowRight size={14} /></button></div></section>
        <section className="info-panel"><ShieldCheck size={23} /><div><h3>Remembered here. Protected here.</h3><p>Profiles and saved passwords are encrypted using {state.platform === 'darwin' ? 'macOS Keychain' : 'Windows DPAPI'}. Passwords are only supplied to the local OpenVPN engine when needed. Forget a saved password from its profile menu.</p><p className="subtle">DropoVPN follows your profile’s routes. This version does not include a kill switch.</p></div></section>
      </>}
      </main><footer className="app-footer"><span>A calmer connection.</span><span>dropovpn <Droplet size={11} /></span></footer>
    </div>
    {connection.status === 'credentials-required' && <Modal title={connection.prompt === 'Private Key' ? 'Unlock your certificate.' : 'Welcome to your connection.'} close={() => api && run(() => api.disconnect())}><p className="modal-copy">{connection.message}</p><form onSubmit={submitCredentials}>{connection.prompt !== 'Private Key' && <label>Username<input autoComplete="username" value={username} required maxLength={4096} onChange={e => setUsername(e.target.value)} placeholder="Your VPN username" /></label>}<label>{connection.prompt === 'Private Key' ? 'Certificate password' : 'Password'}<input type="password" autoComplete="current-password" value={password} required maxLength={4096} onChange={e => setPassword(e.target.value)} placeholder="Your password" /></label>{connection.prompt !== 'Private Key' && <label className="checkbox-label"><input type="checkbox" checked={remember} onChange={e => setRemember(e.target.checked)} /><span>Remember me on this device<small>Encrypted with {state.platform === 'darwin' ? 'macOS Keychain' : 'Windows DPAPI'}.</small></span></label>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy} type="submit">{busy ? <LoaderCircle className="spin" size={17} /> : <LockKeyhole size={16} />}Sign in & connect<ArrowRight size={16} /></button></form></Modal>}
    {renaming && <Modal title="A name that feels familiar." close={() => setRenaming(null)}><form onSubmit={e => { e.preventDefault(); if (api) void run(async () => { await api.rename(renaming.id, name); setRenaming(null); }); }}><label>Profile name<input value={name} onChange={e => setName(e.target.value)} maxLength={80} required /></label><button className="button primary" disabled={busy}>Save name<Check size={16} /></button></form></Modal>}
  </div>;
}
